id: P010459
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:50:58.257340
source_metadata:
  id: bdr:W1KG18532
  title: ཤའི་ཉེས་དམིགས་གནད་ཀྱི་མེ་བཙའ།
  author: ''
  volumes:
    505db6a96c7c4a229e65f82c15c60f04:
      image_group_id: I1KG18551
      title: ''
      volume_number: 1
      total_pages: 88
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
