id: IE76F5A6F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T19:09:37+00:00'
last_modified: '2022-06-08T13:45:39.874976+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18532
  title: ཤའི་ཉེས་དམིགས་གནད་ཀྱི་མེ་བཙའ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2545':
      image_group_id: I1KG18551
      title: ''
      total_pages: 88
      order: 1
      base_file: 2545.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
